# action.yml
name: 'SoonerReport'
description: 'Automated recruiting updates from 247Sports and Rivals.'
inputs:
  target_year:
    description: 'Which year to query for.'
    required: true
    default: '2022'
  target_school:
    description: 'Which school to query for.'
    required: true
    default: 'Georgia Tech'
  slack_enabled:
    description: 'If you want Slack posts enabled. If so, you must configure the environment variables below.'
    required: false
    default: false
  slack_bot_user_oauth_token:
    description: "Slack Bot User OAuth Token. Head to api.slack.com for more details."
    required: false
  slack_channel:
    description: "Slack Channel to post to. Head to api.slack.com for more details."
    required: false
  slack_username:
    description: "Slack Username for the bot. Head to api.slack.com for more details."
    required: false
  slack_incoming_webhook_url:
    description: "Slack Webhook to use for the bot. Head to api.slack.com for more details."
    required: false
  slack_send_empty_updates:
    description: "If you want to send updates to slack when there aren't any new recruits to post about."
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    TARGET_YEAR: ${{ inputs.target_year }}
    TARGET_SCHOOL: ${{ inputs.target_school }}
    SLACK_ENABLED: ${{ inputs.slack_enabled }}
    SLACK_BOT_USER_OAUTH_TOKEN: ${{ inputs.slack_bot_user_oauth_token }}
    SLACK_INCOMING_URL_PREFIX: ${{ inputs.slack_incoming_webhook_url }}
    SLACK_USERNAME: ${{ inputs.slack_username }}
    SLACK_CHANNEL: ${{ inputs.slack_channel }}
    SLACK_SEND_EMPTY_UPDATES: ${{ inputs.slack_send_empty_updates }}
