name: Build and Push Docker Image

on:
  push:
    branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Set repo name as lowercase
        run: |
            BASE_REPO_NAME=${{ github.repository }}
            echo REPOSITORY_NAME="${BASE_REPO_NAME,,}" >> $GITHUB_ENV
      - name: Build and Push Docker Image
        uses:  mr-smithers-excellent/docker-build-push@v5.5
        with:
          image: ${{ env.REPOSITORY_NAME }}
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          push: true # Will only build if this is not here
          tags: |
            latest
