name: Build and Push Docker Image

on:
  push:
    branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set repo name as lowercase
        run: |
            BASE_REPO_NAME=${{ github.repository }}
            echo REPOSITORY_NAME="${BASE_REPO_NAME,,}"
            echo REPOSITORY_URL="ghcr.io/${REPOSITORY_NAME}:latest"
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true # Will only build if this is not here
          tags: |
            ${REPOSITORY_URL}
