name: SoonerReport Scheduled Run
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
    reporter:
        runs-on: ubuntu-latest
        name: Posting latest recruit predictions
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Pull recruit reports and post to Slack
            uses: docker://ghcr.io/akeaswaran/soonerreport:latest
            env:
              TARGET_YEAR: "2022"
              TARGET_SCHOOL: 'Georgia Tech'
              TARGET_RIVALS_PREFIX: 'georgiatech'
              TARGET_247_PREFIX: "georgia-tech"
              SLACK_ENABLED: true
              SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_TOKEN }}
              SLACK_INCOMING_URL_PREFIX: ${{ secrets.SLACK_INCOMING_URL_PREFIX }}
              SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
              SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
              SEND_EMPTY_UPDATES: false
              TWITTER_ENABLED: false
          - name: Update last_updated date file
            run: python ./update_latest.py
          - name: Push last_updated file
            uses: test-room-7/action-update-file@v1.5.0
            with:
              file-path: last_updated.json
              commit-msg: "Updated last_updated.json date after latest bot run."
              github-token: ${{ secrets.GITHUB_TOKEN }}

