name: Scheduled Bot
on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
    SoonerReport:
        runs-on: ubuntu-latest
        name: Pulling latest recruit predictions
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Pull recruit reports and post to Slack
            uses: ./
            with:
              target_school: 'Georgia Tech'
              target_year: "2022"
              slack_enabled: true
              slack_channel: ${{ secrets.SLACK_CHANNEL }}
              slack_username: ${{ secrets.SLACK_USERNAME }}
              slack_bot_user_oauth_token: ${{ secrets.SLACK_BOT_USER_OAUTH_TOKEN }}
              slack_incoming_webhook_url: ${{ secrets.SLACK_INCOMING_URL_PREFIX }}
          - name: Update last_updated
            uses: kludex/update-file@0.6.1
            with:
              script_file: update_latest.py
              update_file: last_updated.json
