name: SoonerReport Scheduled Run
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
    SoonerReport:
        runs-on: ubuntu-latest
        name: Pulling latest recruit predictions
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Set repo name as lowercase
            run: |
                BASE_REPO_NAME=${{ github.repository }}
                USER_NAME=${{ github.repository_owner }}
                USER_NAME="${USER_NAME}/"
                LOWER_CASE_NAME="${BASE_REPO_NAME,,}"
                REPOSITORY_NAME="${LOWER_CASE_NAME}"
                echo REPOSITORY_URL="docker://ghcr.io/${REPOSITORY_NAME}:latest" >> $GITHUB_ENV
          - name: Pull recruit reports and post to Slack
            uses: ${{ env.REPOSITORY_URL }}
            env:
              TARGET_YEAR: 'Georgia Tech'
              TARGET_SCHOOL: "2022"
              SLACK_ENABLED: true
              SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_TOKEN }}
              SLACK_INCOMING_URL_PREFIX: ${{ secrets.SLACK_INCOMING_URL_PREFIX }}
              SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
              SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
              SLACK_SEND_EMPTY_UPDATES: false
          - name: Update last_updated date file
            run: python ./update_latest.py
          - name: Push last_updated file
            uses: test-room-7/action-update-file@v1.5.0
            with:
              file-path: last_updated.json
              commit-msg: "Updated last_updated.json date after latest bot run."
              github-token: ${{ secrets.GITHUB_TOKEN }}

