name: SoonerReport Scheduled Run
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
    SoonerReport:
        runs-on: ubuntu-latest
        name: Pulling latest recruit predictions
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Pull recruit reports and post to Slack
            uses: ./
            with:
              target_school: 'Georgia Tech'
              target_year: "2022"
              slack_enabled: true
              slack_channel: ${{ secrets.SLACK_CHANNEL }}
              slack_username: ${{ secrets.SLACK_USERNAME }}
              slack_bot_user_oauth_token: ${{ secrets.SLACK_BOT_USER_OAUTH_TOKEN }}
              slack_incoming_webhook_url: ${{ secrets.SLACK_INCOMING_URL_PREFIX }}
          - name: Update last_updated date file
            run: python ./update_latest.py
          - name: Push last_updated file
            uses: test-room-7/action-update-file@v1.5.0
            with:
              file-path: last_updated.json
              commit-msg: "Updated last_updated.json date after latest bot run."
              github-token: ${{ secrets.GITHUB_TOKEN }}

